# ?????? ?? ??????? ?????????? ??????? (TMS)
allure.link.tms.pattern=https://your-tms.com/test/{}
allure.link.issue.pattern=https://your-jira.com/browse/{}
allure.link.custom-link.pattern=https://confluence.company.com/page/{}

# ?????????? ? ????????????
allure.results.directory=build/allure-results

# ????????? ????????? ??? ??????
allure.categories.bug.title=????
allure.categories.bug.matchedStatuses=failed
allure.categories.feature.title=????? ????
allure.categories.feature.matchedStatuses=passed