base.url = https://demoqa.com
deleteAccount.url = /Account/v1/User/
generateToken.url = /Account/v1/GenerateToken
login.uri = /Account/v1/Login
registration.url = /Account/v1/User
getInfoAccount.url = /Account/v1/User/
authorized.url= /Account/v1/Authorized
api.baseUrl = https://demoqa.com


getAllBook.url = /BookStore/v1/Books
sdd = /BookStore/v1/Books
userName = IvanP
password = Test!@#$%1

